theme: jekyll-theme-leap-day
title: Linwood's Data Discovery
description: The home base for all of Linwood Creekmore's data science projects, code, analytics, visualizations, and tips.
# Do not copy these file to the output directory
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://lh3.googleusercontent.com/-C5reTxGkmlY/VBxM7TKwh7I/AAAAAAAAA5w/-nq2eAJ58jcSUvXNYyo8LyX1CGqysE_rwCEw/w140-h139-p/LinwoodCartoon.tif
exclude: [ README.md Untitled.ipynb]
url: https://linwoodc3.github.io/
name: Linwood Creekmore III
markdown: kramdown
google_analytics: UA-98331272-1
show_downloads: true
sitemap: true
author:
    twitter: linwoodc3
    picture:
social:
  name: Linwood Creekmore
  links:
    - https://twitter.com/linwoodc3
    - https://www.linkedin.com/in/linwood-creekmore-iii-a2174538
    - https://plus.google.com/u/0/+LinwoodCreekmore
    - https://github.com/linwoodc3
footer-links:
  dribbble:
  email: valinvescap@gmail.com
  facebook: 
  flickr:
  github: linwoodc3
  instagram:
  linkedin: https://www.linkedin.com/in/linwood-creekmore-iii-a2174538
  pinterest:
  rss: datajourney
  twitter: linwoodc3
  stackoverflow: users/4205207/linwoodc3
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: u/0/+LinwoodCreekmore 
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  
